# Generated by Django 4.0.4 on 2022-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_rename_price_retailprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='key_account',
            field=models.BooleanField(default=False),
        ),
    ]
