# Generated by Django 4.0.4 on 2022-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0004_shop_key_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ka_price',
            new_name='key_acc_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ma_price',
            new_name='map_price',
        ),
    ]
