# Generated by Django 4.0.4 on 2022-06-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_remove_retailprice_shop_page_shop_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='retailprice',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
