# Generated by Django 4.0.4 on 2022-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_rename_shop_id_page_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(max_length=9999),
        ),
    ]
