# Generated by Django 4.0.4 on 2022-06-06 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0010_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
    ]
