# Generated by Django 4.0.4 on 2022-06-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0013_remove_page_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
    ]
