# Generated by Django 4.0.4 on 2022-06-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0014_alter_page_source_alter_shop_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
    ]
