# Generated by Django 4.0.4 on 2022-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0015_alter_page_source_alter_shop_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
