# Generated by Django 4.0.4 on 2022-06-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_mapprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='map_price_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.mapprice'),
        ),
    ]
