# Generated by Django 4.0.4 on 2022-06-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_product_map_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='map_price_1',
        ),
    ]
