# Generated by Django 4.0.4 on 2022-06-08 12:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0023_mapprice_product_alter_mapprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAccPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reporter.product')),
            ],
        ),
    ]
