# Generated by Django 4.0.4 on 2022-06-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0025_retailprice_curr_map_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailprice',
            old_name='curr_map_price',
            new_name='curr_target_price',
        ),
    ]
