# Generated by Django 4.0.4 on 2022-06-10 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0026_rename_curr_map_price_retailprice_curr_target_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailprice',
            name='curr_target_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
    ]
