# Generated by Django 4.0.4 on 2022-06-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0027_alter_retailprice_curr_target_price'),
        ('reporter', '0028_remove_song_category_delete_genre_delete_song'),
    ]

    operations = [
    ]
