# Generated by Django 4.0.4 on 2022-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0029_merge_20220614_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(to='reporter.product'),
        ),
    ]
