# Generated by Django 4.0.4 on 2022-06-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0029_merge_20220610_1657'),
        ('reporter', '0029_merge_20220614_1127'),
    ]

    operations = [
    ]
