# Generated by Django 4.0.4 on 2022-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0030_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(to='reporter.product'),
        ),
    ]
