# Generated by Django 4.0.4 on 2022-06-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0030_merge_20220615_1057'),
        ('reporter', '0030_merge_20220615_1058'),
    ]

    operations = [
    ]
