# Generated by Django 4.0.4 on 2022-06-16 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0031_merge_20220616_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Επιτρέπονται μόνο αριθμοί (0-9). Μέχρι 10 χαρακτήρες. π.χ. 2310123456', regex='\\d{9,10}$')]),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(through='reporter.RetailPrice', to='reporter.product'),
        ),
    ]
