# Generated by Django 4.0.4 on 2022-06-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0031_shop_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
    ]
