# Generated by Django 4.0.4 on 2022-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0032_remove_shop_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(through='reporter.RetailPrice', to='reporter.product'),
        ),
    ]
