# Generated by Django 4.0.4 on 2022-06-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0036_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
