# Generated by Django 4.0.4 on 2022-06-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0040_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
