# Generated by Django 4.0.4 on 2022-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0041_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder_img.png', upload_to='product_images'),
        ),
    ]
