# Generated by Django 4.0.4 on 2022-06-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0043_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product_images/placeholder_img.png', upload_to='product_images')),
            ],
        ),
    ]
