# Generated by Django 4.0.4 on 2022-06-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0044_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
