# Generated by Django 4.0.4 on 2022-06-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0047_remove_product_image_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/placeholder_img.png', upload_to='product_images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
