# Generated by Django 4.0.5 on 2022-07-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0052_alter_shop_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='source',
        ),
        migrations.AddField(
            model_name='retailprice',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reporter.source'),
        ),
    ]
