# Generated by Django 4.0.6 on 2022-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0053_remove_shop_source_retailprice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wc_prod_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
