# Generated by Django 4.0.6 on 2022-07-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0054_product_wc_prod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wc_prod_id',
        ),
    ]
