# Generated by Django 4.0.6 on 2022-07-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0055_remove_product_wc_prod_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyAccPrice',
        ),
    ]
