# Generated by Django 4.1 on 2022-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0058_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='Product name', max_length=200),
        ),
    ]
