# Generated by Django 4.1 on 2022-08-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0062_rename_name2_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
