# Generated by Django 4.1 on 2022-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0063_remove_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
