# Generated by Django 4.1 on 2022-09-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0065_retailprice_original_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporter.product",
            ),
        ),
    ]
