# Generated by Django 4.1 on 2022-09-21 08:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0067_alter_page_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mapprice",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporter.product",
            ),
        ),
    ]
