# Generated by Django 4.1 on 2022-09-22 12:48

from django.db import migrations, models
import django.db.models.deletion
import reporter.models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0072_alter_mapprice_price_alter_mapprice_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                default=reporter.models.get_default_manufacturer,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="reporter.manufacturer",
            ),
        ),
    ]
