# Generated by Django 4.1 on 2022-09-22 12:53

from django.db import migrations, models
import django.db.models.deletion
import reporter.models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0073_alter_product_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_category",
            field=models.ForeignKey(
                default=reporter.models.get_default_category,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="reporter.category",
            ),
        ),
    ]
