# Generated by Django 4.1 on 2022-12-07 07:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0074_alter_product_main_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="map_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="retailprice",
            name="curr_target_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="retailprice",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="retailprice",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
    ]
